# Generated by Django 4.1.7 on 2023-03-16 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={
                "ordering": ["-created_at", "title", "read_time"],
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
