# Generated by Django 4.1.7 on 2023-03-30 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0002_newspaper_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
        ),
        migrations.CreateModel(
            name="NewsInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("day", models.DateField()),
                (
                    "articles",
                    models.ManyToManyField(
                        related_name="news_of_the_day", to="news.newsarticle"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News Instance",
                "verbose_name_plural": "News Instances",
                "ordering": ["-day"],
            },
        ),
    ]
