# Generated by Django 4.1.7 on 2023-03-30 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_newsarticle_options_newsinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsinstance",
            name="day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
