# Generated by Django 4.1.7 on 2023-03-30 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_newsinstance_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsinstance",
            name="day",
            field=models.DateField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
    ]
