# Generated by Django 4.1.7 on 2023-03-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_category_article_newsarticle_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articlecategories",
                to="news.category",
            ),
        ),
    ]
