# Generated by Django 4.1.7 on 2023-03-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_newsinstance_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsinstance",
            name="newspaper",
            field=models.ForeignKey(
                default="ff9b4db8-3d52-410b-b5b5-b666dd823cf1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newspaper_instance",
                to="news.newspaper",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsinstance",
            name="day",
            field=models.DateField(),
        ),
    ]
