# Generated by Django 4.1.7 on 2023-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_newsarticle_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="articles",
            field=models.ManyToManyField(
                related_name="categories", to="news.newsarticle"
            ),
        ),
    ]
