# Generated by Django 4.1.7 on 2023-03-30 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_newsinstance_newspaper_alter_newsinstance_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="newspaper",
        ),
    ]
