# Generated by Django 4.1.7 on 2023-03-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_remove_newsarticle_newspaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="newspaper",
            field=models.ManyToManyField(related_name="articles", to="news.newspaper"),
        ),
    ]
