# Generated by Django 4.1.7 on 2023-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_movie_movielistname_alter_playlist_tracks_movielist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movielist",
            name="movie",
        ),
        migrations.AddField(
            model_name="movielist",
            name="movie",
            field=models.ManyToManyField(related_name="movies", to="playlists.movie"),
        ),
    ]
