# Generated by Django 4.1.7 on 2023-03-24 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_remove_movielist_movie_movielist_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movielist",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="movielist",
            name="name",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="MovieList",
        ),
        migrations.DeleteModel(
            name="MovieListName",
        ),
    ]
