# Generated by Django 4.1.7 on 2023-03-29 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0004_remove_movielist_movie_remove_movielist_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovieStore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="moviestore", to="playlists.movie"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
