# Generated by Django 4.1.7 on 2023-03-29 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0005_movie_moviestore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "movies",
                    models.ManyToManyField(related_name="genre", to="playlists.movie"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="MovieStore",
        ),
    ]
