# Generated by Django 4.1.7 on 2023-03-29 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0006_genre_delete_moviestore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("day", models.CharField(max_length=400)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre",
                        to="playlists.genre",
                    ),
                ),
                (
                    "movies",
                    models.ManyToManyField(related_name="movies", to="playlists.movie"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
