# Generated by Django 4.1.7 on 2023-03-29 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0007_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("day", models.CharField(max_length=400)),
                (
                    "genre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playlists.genre",
                    ),
                ),
                (
                    "movies",
                    models.ManyToManyField(
                        related_name="movies_of_the_day", to="playlists.movie"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
