# Generated by Django 4.1.7 on 2023-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0008_dailyrecommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyrecommendation",
            name="day",
            field=models.CharField(default="", max_length=400),
        ),
    ]
