# Generated by Django 4.1.7 on 2023-03-29 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0010_alter_genre_movies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="movies",
        ),
    ]
