# Generated by Django 4.1.7 on 2023-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_editor",
            field=models.BooleanField(default=False),
        ),
    ]
