# Generated by Django 4.1.7 on 2023-04-01 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlebookmark",
            name="user",
        ),
        migrations.AddField(
            model_name="articlebookmark",
            name="bookmarker",
            field=models.ForeignKey(
                default="6dc7694b-cd94-4ad4-8226-ddd3a2d845f7",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
